### ISSUE TITLE
MIRROR

### ISSUE THREAD

**Issue by 89z** [vgarleanu/yarr#1]
If I change the mirror to `rarbg.to`, the code stops working:

https://github.com/vgarleanu/yarr/blob/e85bbbc52aa7c01f4e0a391f3f9bbed03c5fca90/src/main.rs#L11

do you know why?

**Comment by vgarleanu** [comment]
This lib is basically unfinished at the moment. The scraper might be out-of-date or perhaps the new domain uses some other captcha system.

**Comment by 89z** [comment]
I got it working here:

https://github.com/89z/torrent/tree/master/rarbg.to
